theme = "hugo-now-ui"
baseURL = "conservation-gym/"
languageCode = "en-us"
title = "RL for Conservation"
googleAnalytics = "UA-179064457-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_cache$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$"]
#enableGitInfo = true
publishDir = "docs/"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Introduction"
    url = "#intro"
    pre = "<i class='fa fa-rocket'></i>"
    weight = 1
[[menu.main]]
    name = "Develop Environments"
    url = "#Environments"
    pre = "<i class='now-ui-icons design_app'></i>"
    weight = 2
[[menu.main]]
    name = "Train Agents"
    url = "#Agents"
    pre = "<i class='fa fa-fighter-jet'></i>"
    weight = 3
[[menu.main]]
    name = "Leaderboard"
    url = "#Leaderboard"
    pre = "<i class='fa fa-trophy'></i>"
    weight = 4
[[menu.main]]
    name = "Contribute"
    url = "#Contribute"
    pre = "<i class='fa fa-user'></i>"
    weight = 5


[[menu.footer]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/cboettig"
    weight = 1
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/cboettig"
    weight = 2
[[menu.footer]]
    identifier = "copyright"
    name = "MIT"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "https://spdx.org/licenses/MIT"
    weight = 3


[params]
    background = "img/icy-sugar-cubes.jpg"
    tint = "blue"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"




